sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MGkwJHSHRj8zeFXnTi0gy4PZSsIQxYM+2/Vfcl3kLyWRYo7oBcLUt1n70RpraxFnGyTaKQH1d697ydYob9uvmUC+QYJnnxVyMW7raR0Z2bWkFY4g1Mb8x1E0kUMNk0NFaWGKINNz04GMRdiXa1NEFJKZAYrgLtUco46Zt+ODTPawImrxgrchLVh13TTjPkjdaoH/6D+kC70/Ne4wryKETFO6xd2UUWbU+dmflEXWFMMBAByX1vGRDDEK3vsyARuA2W1L/RJxmoh5kY40aGCW2yhiPqcAfjT7il+iMbNNmUoVo52EX0JAs91QcYy6joBGnZj6rQPKTLwFhoAAIpwZXJ2TRb57xEAhoLYfEliECUPYipUskfwTDfjv/IYtawwLutyhXfSRf6dqEPz9HzgSy++WOuU7IJgi28zxt+qpABNUKSp54ivuy5Suo0lX73GJFqYN+9bKfj6B+JLltiXwVnmCED7TueNTDePaR2Rqkcj7YMkXL1f1biIQtW1Jy5Pz5HCRa+GnRuAOd8MPCroZqeiy8oc0/NeRbVAF4ZE0+BogdvARpiuYdWXIZxD5BnM/IfBv1o5Tw6EZ8XZAFCLsAFwcp/XGeExNi4XE33uxmDN+sZj722+27YDFn33qgQwhnVUZWxePqmrw2ZMg0tM4nSe8y5ieUM2CIDzOCwIv558=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Imaginary-Portraits_4038
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy